- name: install nginx
  become: yes
  yum: name=nginx state=present

- name: create the user that the nginx process will run as
  become: yes
  user: name={{ nginx_user }}

  #see nginx/README.md
- name: set httpd_can_network_connect bit and make it persistent 
  become: yes
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: copy nginx.conf
  become: yes
  template: src=nginx.conf.j2 dest={{ nginx_config_dir }}/nginx.conf backup=yes
  notify: reload nginx config

- name: create nginx sites-available directory
  become: yes
  file: path={{ nginx_config_dir }}/sites-available state=directory

- name: copy default site
  become: yes
  template: src=sites-available/default.j2 dest={{ nginx_config_dir }}/sites-available/default backup=yes
  notify: reload nginx config