---
- hosts: control
  roles: 
    - { role: common, become: yes }

- hosts: database
  roles: 
    - { role: common, become: yes }
    - { role: mongodb, become: yes }
  
- hosts: appserver
  tasks:
    - name: debug variables
      debug: var={{ repo_url }}
      
    - name: checkout repo from git
      git: 
        clone: yes
        dest: "{{ working_dir }}"
        repo: "{{ repo_url }}"
        accept_hostkey: yes
      register: checkout_completed

    - name: install npm packages for application
      npm: 
        path: "{{ working_dir }}/app"
        production: yes
      when: checkout_completed.changed 

    - name: start node app with pm2
      become: yes
      command: pm2 start -f index.js chdir={{ working_dir }}/app 

  roles: 
    - { role: common, become: yes }
    - { role: nodejs, become: yes }
    - { role: nginx, become: yes }